-- Tabla Cuontries 

INSERT INTO Countries ( Name_Country, postal_code , Continent ) VALUES ('Colombia' ,123456 , 'America' );
INSERT INTO Countries ( Name_Country, postal_code , Continent ) VALUES ('Mexico' ,903456 , 'America' );
INSERT INTO Countries ( Name_Country, postal_code , Continent ) VALUES ('Austria' ,666456 , 'Europa' );
INSERT INTO Countries ( Name_Country, postal_code , Continent ) VALUES ('Italia' ,789564 , 'Europa' );
INSERT INTO Countries ( Name_Country, postal_code , Continent ) VALUES ('Nigeria' ,987123 , 'Africa' );
INSERT INTO Countries ( Name_Country, postal_code , Continent ) VALUES ('Kongo' ,983456 , 'Africa' );
INSERT INTO Countries ( Name_Country, postal_code , Continent ) VALUES ('China' ,183456 , 'Asia' );
INSERT INTO Countries ( Name_Country, postal_code , Continent ) VALUES ('Japon' ,980456 , 'ASia' );



-- Tabla Customer_Category

INSERT INTO customer_category (name_customer_category , discount , description) VALUES ('standard' , 0 , 'Usuario sin ningun tipo de beneficio' );
INSERT INTO customer_category (name_customer_category , discount , description) VALUES ('gold' , 1.5 , 'Usuario que paga la membresia gold' );
INSERT INTO customer_category (name_customer_category , discount , description) VALUES ('premium' , 2.0, 'Usuario que paga la membresia gold y ademas recomienda nuestra pagina a otros usuarios por medio de su codigo unico' );


-- Customers

insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (1, 'Midge', 'Kegan', 'mkegan0@newyorker.com', '685-403-4845', 'eHT8VfL', '50 Forest Run Junction', '2022-01-27', 2, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (2, 'Thatch', 'Acum', 'tacum1@yahoo.com', '335-686-1383', 'FS5o3fZ708', '7950 Washington Junction', '2022-01-08', 8, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (3, 'Kalvin', 'Giacomello', 'kgiacomello2@cbslocal.com', '860-757-3118', 'UBPfILk', '7253 Doe Crossing Way', '2020-12-11', 3, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (4, 'Ardith', 'Phibb', 'aphibb3@privacy.gov.au', '539-297-5731', 'ircBgmAg', '65935 Farwell Trail', '2020-04-08', 7, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (5, 'Harlen', 'Ferrie', 'hferrie4@creativecommons.org', '542-880-2288', 'cqjvr9nPkN', '39 Marcy Terrace', '2021-06-19', 6, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (6, 'Kellina', 'Fenny', 'kfenny5@tumblr.com', '842-579-1425', 'KNbWJlEV5x', '0261 Victoria Pass', '2020-02-26', 8, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (7, 'Hall', 'Rosenvasser', 'hrosenvasser6@alibaba.com', '423-145-0126', 'xGs7cuYbdOzS', '2 Eagan Center', '2019-08-28', 5, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (8, 'Bailey', 'Harp', 'bharp7@google.it', '619-279-9593', 'XzljbRb', '8928 Daystar Parkway', '2021-09-01', 1, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (9, 'Maude', 'Minett', 'mminett8@ox.ac.uk', '401-460-8725', 'kaPBQ5', '6 Pierstorff Way', '2022-04-02', 5, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (10, 'Bobine', 'Antognelli', 'bantognelli9@phoca.cz', '280-396-0700', 'I6BJbT', '2262 East Center', '2021-08-16', 8, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (11, 'Grayce', 'Glenn', 'gglenna@umich.edu', '485-852-5808', 'gRZECdR', '3 Westport Crossing', '2021-09-26', 2, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (12, 'Morganne', 'Kleinhandler', 'mkleinhandlerb@cbc.ca', '819-972-9454', 'tUgbRXjyxd', '430 Barnett Trail', '2022-01-13', 3, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (13, 'Ogdon', 'Cosyns', 'ocosynsc@about.com', '527-587-3133', 'uEmxwq', '2 Oak Valley Parkway', '2020-06-17', 1, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (14, 'Gabbie', 'Burvill', 'gburvilld@fotki.com', '589-849-7722', 'jKJ9wUBSV7', '47923 Holy Cross Avenue', '2021-04-17', 8, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (15, 'Westbrook', 'Pellingar', 'wpellingare@aboutads.info', '818-920-7623', 'bwRbyZ', '51 Lake View Alley', '2019-02-07', 5, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (16, 'Mahalia', 'Surfleet', 'msurfleetf@smh.com.au', '724-994-7114', 'd7VDaGSLD', '349 Talisman Street', '2019-02-17', 1, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (17, 'Constantine', 'Rands', 'crandsg@symantec.com', '224-773-1505', 'BXrrO19ESXrt', '4775 Jenifer Plaza', '2021-10-01', 8, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (18, 'Christian', 'Duffrie', 'cduffrieh@gmpg.org', '972-413-2126', 'P2IJj6fw', '51 Utah Parkway', '2020-06-25', 6, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (19, 'Cathi', 'Glowacz', 'cglowaczi@github.com', '135-496-1196', 'YjLMzo0vv', '77 Orin Place', '2022-07-10', 2, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (20, 'Matthew', 'Cess', 'mcessj@meetup.com', '314-506-1269', 'HlmFFkbRI', '4439 Cascade Pass', '2020-04-04', 8, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (21, 'Abra', 'Beddin', 'abeddink@icq.com', '559-179-5193', '05SIiBV', '67 Rowland Alley', '2022-07-15', 8, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (22, 'Natassia', 'Kennifick', 'nkennifickl@omniture.com', '780-695-0095', 'NGQLTwM', '5931 Shelley Drive', '2019-05-18', 8, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (23, 'Tomlin', 'Braxton', 'tbraxtonm@mlb.com', '511-215-1551', 'i3Sixcd', '064 Thierer Avenue', '2019-07-19', 5, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (24, 'Verine', 'Toffanelli', 'vtoffanellin@ca.gov', '848-171-1457', 'J9j8rzYYJ', '9 Northridge Junction', '2019-03-19', 3, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (25, 'Robina', 'Reignolds', 'rreignoldso@alibaba.com', '960-347-4023', 'S4MntvyX', '44778 Maywood Point', '2022-07-18', 5, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (26, 'Elisha', 'Tree', 'etreep@goodreads.com', '717-138-3247', 'rDkCcb', '937 Green Drive', '2020-04-19', 1, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (27, 'Amery', 'Spilstead', 'aspilsteadq@pagesperso-orange.fr', '312-848-9562', '2z81H8EiPls', '39640 Claremont Pass', '2021-06-11', 5, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (28, 'Claybourne', 'Duiged', 'cduigedr@phoca.cz', '780-242-2328', '7jZh0f', '24041 Ohio Avenue', '2019-07-18', 1, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (29, 'Briny', 'Whenham', 'bwhenhams@virginia.edu', '966-372-7786', 'H0ilZXC54i6Q', '5301 Hallows Place', '2021-12-21', 6, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (30, 'Valentina', 'Eldredge', 'veldredget@ning.com', '267-406-2066', 'rMkiOmTo9Oe', '7 Eagle Crest Parkway', '2020-09-23', 7, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (31, 'Arabella', 'Obal', 'aobalu@ed.gov', '504-434-6527', 'WT3b4j', '6 Maywood Crossing', '2019-01-04', 2, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (32, 'Dalenna', 'Frowde', 'dfrowdev@wordpress.com', '859-817-0451', 'C7kQeoHV8', '3619 Esch Place', '2018-11-27', 5, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (33, 'Eb', 'Wardingley', 'ewardingleyw@istockphoto.com', '796-600-1608', 'v1J5yvYflDym', '572 Bonner Trail', '2022-01-06', 2, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (34, 'Marcellina', 'Aldhouse', 'maldhousex@tumblr.com', '134-818-0011', 'dlpsR2', '72949 Roxbury Lane', '2018-11-18', 1, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (35, 'Arline', 'Swatridge', 'aswatridgey@jugem.jp', '325-726-6783', 'XFIpYeoiUNo', '1441 Mcbride Road', '2020-03-15', 8, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (36, 'Willard', 'Bernocchi', 'wbernocchiz@deviantart.com', '673-466-9692', 'wU8X4VeBv', '75 Service Hill', '2021-03-18', 7, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (37, 'Egon', 'D''Agostini', 'edagostini10@patch.com', '288-459-5068', 'gF3XDD9kA', '9 Hayes Park', '2018-09-28', 2, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (38, 'Giacopo', 'McCarthy', 'gmccarthy11@cam.ac.uk', '260-792-6285', '2bDbbcw', '7 Westridge Way', '2020-08-30', 2, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (39, 'Joeann', 'Heald', 'jheald12@google.de', '735-597-7002', 'j7tiNDl', '08 Bultman Center', '2019-06-07', 2, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (40, 'Shannon', 'Densun', 'sdensun13@yolasite.com', '894-422-7677', 'xVe315PUHv1q', '32 Canary Circle', '2021-04-22', 7, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (41, 'Jemie', 'Seldner', 'jseldner14@blinklist.com', '942-223-3880', 'EosX3fF3Il', '125 Crest Line Circle', '2022-05-05', 2, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (42, 'Hanny', 'MacAllister', 'hmacallister15@simplemachines.org', '177-728-7855', 'Rj6IWJQkm', '77 Northland Plaza', '2019-10-29', 4, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (43, 'Roy', 'Marlor', 'rmarlor16@bizjournals.com', '581-102-0127', 'YXFqrzp5rUc', '99 Corry Hill', '2019-01-18', 7, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (44, 'Win', 'Schlagtmans', 'wschlagtmans17@marketwatch.com', '839-772-6017', 'KBWbu6om5uej', '150 Scoville Drive', '2021-03-05', 1, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (45, 'Emmy', 'McSperron', 'emcsperron18@wsj.com', '581-627-9400', 'RdY37lu7', '15 Service Place', '2021-09-17', 1, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (46, 'Eulalie', 'Shoesmith', 'eshoesmith19@com.com', '592-136-5799', '11mLzalVZWZ', '2 Springview Crossing', '2019-01-07', 6, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (47, 'Illa', 'Baldacchino', 'ibaldacchino1a@skyrock.com', '478-810-5742', '9olVBqVWZL1v', '46 Novick Road', '2019-12-23', 1, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (48, 'Drusi', 'Watt', 'dwatt1b@dagondesign.com', '294-717-0037', 'NtSJwS', '3344 Bultman Hill', '2021-08-24', 5, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (49, 'Borden', 'Greenall', 'bgreenall1c@vistaprint.com', '898-196-2656', 's67hkZ5BKt5', '64218 Stone Corner Trail', '2019-10-16', 6, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (50, 'Duffy', 'Turnbull', 'dturnbull1d@wisc.edu', '578-282-0444', 'BmEP0mVQH', '20 Bunting Park', '2021-02-07', 4, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (51, 'Shayne', 'De Haven', 'sdehaven1e@mashable.com', '140-285-2070', 'rUPGSlkb', '4634 Hagan Court', '2018-09-21', 1, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (52, 'Sapphire', 'Deny', 'sdeny1f@devhub.com', '138-603-1370', '9IHWqwsXjGu', '64044 Clemons Drive', '2019-01-14', 4, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (53, 'Martainn', 'Yankeev', 'myankeev1g@phpbb.com', '976-193-1388', 'phV2SClMXg0M', '66 Mariners Cove Avenue', '2019-03-07', 5, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (54, 'Modestia', 'Dengel', 'mdengel1h@amazon.co.jp', '448-723-6634', '082qRWK2Kp', '3 Elgar Trail', '2021-11-10', 2, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (55, 'Maure', 'Ough', 'mough1i@springer.com', '919-701-5418', 'IybGYblyYEf', '70 Mosinee Alley', '2020-01-11', 8, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (56, 'Lark', 'Urian', 'lurian1j@independent.co.uk', '745-500-4816', 'O4WqY5Ww1C', '850 Hanson Parkway', '2020-02-03', 5, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (57, 'Averill', 'Sobey', 'asobey1k@baidu.com', '269-977-2193', 'WEUIPDf6', '69248 Logan Pass', '2020-07-21', 7, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (58, 'Lancelot', 'Penna', 'lpenna1l@netvibes.com', '322-290-0754', 'hsSaxi', '528 Di Loreto Street', '2019-12-24', 3, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (59, 'Amandy', 'Osbiston', 'aosbiston1m@booking.com', '526-735-9239', 'GCveTCzR', '08 Del Sol Junction', '2021-12-06', 7, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (60, 'Timoteo', 'Fosdike', 'tfosdike1n@baidu.com', '809-967-4876', 'OqDp9crCd', '51151 Harbort Junction', '2020-10-05', 1, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (61, 'Carmelina', 'Valti', 'cvalti1o@squidoo.com', '617-742-8468', 'qKUFX73bui', '99198 Havey Center', '2019-12-12', 2, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (62, 'Udell', 'Piet', 'upiet1p@latimes.com', '801-669-3746', '47PIq02it', '2 Clove Crossing', '2022-01-07', 2, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (63, 'Ambrose', 'Cobello', 'acobello1q@themeforest.net', '675-291-7608', 'vJ0aDW', '136 Marquette Crossing', '2022-04-03', 2, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (64, 'Erick', 'Luna', 'eluna1r@blogs.com', '667-594-9912', 'gR3Hoo', '1 Lerdahl Terrace', '2018-11-14', 2, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (65, 'Kass', 'Saltsberg', 'ksaltsberg1s@xinhuanet.com', '459-336-6333', 'jRMI0yF0f1d', '80 1st Road', '2020-11-21', 1, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (66, 'Clayborne', 'Jiras', 'cjiras1t@census.gov', '780-759-9308', 'ktykCk', '5 Vernon Way', '2019-06-23', 1, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (67, 'Thomasine', 'Rolfo', 'trolfo1u@sourceforge.net', '210-317-8745', '25mLzKF', '243 Barby Point', '2019-02-14', 7, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (68, 'Maxine', 'Keming', 'mkeming1v@github.com', '426-717-4047', 'VXkJeLCTA', '463 Ridge Oak Park', '2020-02-18', 1, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (69, 'Bordy', 'Grass', 'bgrass1w@php.net', '591-596-2830', 'WzzhkK', '1 Graedel Pass', '2020-12-18', 4, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (70, 'Josie', 'Stoodale', 'jstoodale1x@t-online.de', '401-313-2457', '8BXAzH', '2608 Thackeray Junction', '2020-10-23', 3, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (71, 'Ingaborg', 'Stiegers', 'istiegers1y@g.co', '411-939-4123', 'aTuB92vqu1M', '0763 Beilfuss Way', '2019-08-05', 7, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (72, 'Patrick', 'Harbron', 'pharbron1z@gizmodo.com', '662-865-1852', 'j16cjY', '19415 Meadow Ridge Hill', '2022-01-20', 3, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (73, 'Siobhan', 'Guilder', 'sguilder20@un.org', '819-151-8722', 'X6EJFAVx', '408 Jenifer Terrace', '2019-07-23', 8, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (74, 'Tonye', 'Boutell', 'tboutell21@chicagotribune.com', '402-704-5567', 'X4dZ3yoe', '3955 Miller Avenue', '2019-05-05', 3, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (75, 'Sofie', 'Fitzmaurice', 'sfitzmaurice22@si.edu', '238-958-5218', 'd4ScWjwCR8z', '0698 4th Road', '2020-12-06', 6, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (76, 'Sophronia', 'Moret', 'smoret23@tinypic.com', '897-868-4531', '5i8DKWA5i', '8 Pleasure Circle', '2022-06-13', 6, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (77, 'Isacco', 'Thomkins', 'ithomkins24@nyu.edu', '786-872-7961', 'ueTtCtfb7', '35920 Colorado Drive', '2021-10-30', 7, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (78, 'Mathilda', 'Fillingham', 'mfillingham25@purevolume.com', '241-126-8967', 'MSaWpwPHE1', '18483 Surrey Terrace', '2020-10-06', 5, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (79, 'Lucretia', 'Wybron', 'lwybron26@rambler.ru', '848-510-4495', 'R4jLJy4ByPnW', '562 Hanson Parkway', '2022-07-13', 3, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (80, 'Phelia', 'Cuxon', 'pcuxon27@engadget.com', '699-532-9248', 'oSfQc3q15Avm', '1 Calypso Court', '2021-04-05', 7, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (81, 'Rebeka', 'Pierpoint', 'rpierpoint28@nps.gov', '660-165-6697', 'oQzm1wDKW1', '0151 High Crossing Parkway', '2021-11-20', 8, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (82, 'Urban', 'Leere', 'uleere29@ft.com', '157-124-0447', 'MsGjv4YvUbOC', '8 Eastlawn Street', '2020-06-13', 8, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (83, 'Denise', 'Daggett', 'ddaggett2a@about.com', '814-235-9018', 'kmeJUjREDSm', '269 Alpine Trail', '2022-05-26', 5, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (84, 'Eamon', 'Gorcke', 'egorcke2b@archive.org', '259-389-0143', 'fKGb9Y3A', '0749 Pearson Park', '2019-04-13', 4, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (85, 'Freemon', 'Buttrum', 'fbuttrum2c@reverbnation.com', '355-636-5272', 'YV1IsK2Li47A', '18 Michigan Parkway', '2019-07-24', 4, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (86, 'Dorry', 'Warbeys', 'dwarbeys2d@dot.gov', '628-357-5780', 'MxrukVTE', '235 Lindbergh Court', '2020-01-25', 3, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (87, 'Elsinore', 'Simmill', 'esimmill2e@feedburner.com', '691-989-7528', 'RSsWiOkIY6Jn', '3498 Johnson Lane', '2019-07-17', 5, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (88, 'Bram', 'Felce', 'bfelce2f@springer.com', '850-993-1701', 'iiaSHeGZ', '2548 Eagle Crest Alley', '2020-01-12', 6, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (89, 'Tyson', 'Hooban', 'thooban2g@jalbum.net', '355-701-8084', 'rLPvTwf', '9 Pond Center', '2019-11-28', 7, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (90, 'Chrysa', 'Bretelle', 'cbretelle2h@godaddy.com', '309-147-5534', 'lTGzxF', '9 Nevada Alley', '2018-12-06', 5, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (91, 'Robenia', 'Breem', 'rbreem2i@flickr.com', '383-873-3129', 'Yz9Ec9OH', '5664 Elgar Trail', '2022-02-08', 2, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (92, 'Farly', 'Snugg', 'fsnugg2j@economist.com', '599-256-1481', 'QocjJ6', '2048 7th Plaza', '2020-07-17', 7, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (93, 'Neila', 'Alvey', 'nalvey2k@bigcartel.com', '532-478-8114', 'IaZx8o', '36 Spohn Drive', '2021-11-13', 3, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (94, 'Angelika', 'Fantin', 'afantin2l@flickr.com', '994-410-6631', 'NZk8mgkbKNC', '3 Barnett Park', '2020-07-28', 3, 2);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (95, 'Dehlia', 'Drei', 'ddrei2m@prweb.com', '783-334-9630', 'vdmkh9mV4', '820 Oriole Drive', '2020-08-15', 5, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (96, 'Onfre', 'Dadge', 'odadge2n@ebay.co.uk', '467-925-4008', 'GoW9e8G', '4182 Vahlen Junction', '2020-06-15', 3, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (97, 'Miquela', 'Drysdell', 'mdrysdell2o@theguardian.com', '228-651-4721', 'qYIhfKf', '6358 Washington Place', '2021-11-18', 2, 3);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (98, 'Joby', 'Pautot', 'jpautot2p@dot.gov', '413-253-4749', 'qX3R1eU8N', '241 Roxbury Drive', '2020-02-10', 6, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (99, 'Adriano', 'Hevey', 'ahevey2q@newyorker.com', '951-720-4408', 'JR21uzoXVIl5', '02 Knutson Circle', '2022-06-26', 5, 1);
insert into customers (pk_customer, first_name, last_name, email, phone, password_customer, default_shipping_address, date_create_account, fk_countries, fk_customer_category) values (100, 'Madelin', 'Goch', 'mgoch2r@unesco.org', '958-702-8224', 'BgUAcd36J', '050 Caliangt Pass', '2018-10-19', 2, 2);



-- Tabla delivery Companies

INSERT INTO delivery_companies (name_company , phone_contact , email_contact , address_company, fk_countries) VALUES ('Servientrega' , '312 786 90 87' , 'servientrega@domain.com' , 'av 78 # 78 - 90' , 1);
INSERT INTO delivery_companies (name_company , phone_contact , email_contact , address_company, fk_countries) VALUES ('Mexican Express' , '456 786 90 87' , 'MexicanExpress@domain.com' , 'av 909 # 78 - 90' , 2);
INSERT INTO delivery_companies (name_company , phone_contact , email_contact , address_company, fk_countries) VALUES ('Austria Express' , '457 098 90 87' , 'AustriaExpress@domain.com' , 'av 23 # 78 - 90' , 3);
INSERT INTO delivery_companies (name_company , phone_contact , email_contact , address_company, fk_countries) VALUES ('ali Express' , '478 786 90 87' , 'aliExpress@domain.com' , 'av 1 # 78 - 90' , 4);
INSERT INTO delivery_companies (name_company , phone_contact , email_contact , address_company, fk_countries) VALUES ('black Express' , '123 786 90 87' , 'blackExpress@domain.com' , 'av 65 # 78 - 90' , 5);
INSERT INTO delivery_companies (name_company , phone_contact , email_contact , address_company, fk_countries) VALUES ('Lion Express' , '927 786 90 87' , 'LionExpress@domain.com' , 'av 41 # 78 - 90' , 6);
INSERT INTO delivery_companies (name_company , phone_contact , email_contact , address_company, fk_countries) VALUES ('Panda express' , '456 786 90 87' , 'pandaexpress@domain.com' , 'av 37 # 78 - 90' , 7);
INSERT INTO delivery_companies (name_company , phone_contact , email_contact , address_company, fk_countries) VALUES ('Katana Express' , '345 234 90 87' , 'katanaexpress@domain.com' , 'av 09 # 78 - 90' , 8);


-- Tabla Product_Category

INSERT INTO Product_Category (Name_Product_Category ,  Description)values ('Aseo personal' , 'productos usados para el cuidado de la higiene personal');
INSERT INTO Product_Category (Name_Product_Category ,  Description)values ('Tecnología' , 'productos relacionados con electrodomesticos y informatica');
INSERT INTO Product_Category (Name_Product_Category ,  Description)values ('Moda' , 'productos relacionados con ropa sin importar el sexo del usuario');
INSERT INTO Product_Category (Name_Product_Category ,  Description)values ('Auto Partes' , 'repuestos y productos usados para el cuidado de vehiculos');
INSERT INTO Product_Category (Name_Product_Category ,  Description)values ('Moto Partes' , 'repuestos y productos usados para el cuidado de las motociletas');
INSERT INTO Product_Category (Name_Product_Category ,  Description)values ('Calzado' , 'productos realcionados con cualquier tipo de calzado botas, tenis, zapatos , etc');


-- Tabla products

insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (1, 'Wine - Ice Wine', 63.0, 'non velit nec nisi vulputate nonummy', 400, 1774.93, 3, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (2, 'Wine - George Duboeuf Rose', 24.61, 'nulla quisque arcu libero', 459, 825.71, 3, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (3, 'Wine - Taylors Reserve', 53.87, 'quis justo maecenas rhoncus aliquam lacus', 485, 3558.75, 6, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (4, 'Flavouring - Orange', 18.87, 'et magnis dis parturient montes nascetur', 325, 832.08, 3, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (5, 'Snapple - Iced Tea Peach', 29.93, 'tincidunt eget tempus vel', 219, 4659.33, 5, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (6, 'Oregano - Dry, Rubbed', 37.4, 'integer aliquet massa id lobortis convallis', 25, 3341.83, 6, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (7, 'Beans - French', 37.93, 'morbi quis tortor', 67, 4658.3, 4, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (8, 'Wine - Lou Black Shiraz', 22.53, 'platea dictumst morbi vestibulum velit', 479, 2307.15, 5, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (9, 'Cheese - Wine', 40.88, 'proin at turpis a', 340, 2869.04, 4, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (10, 'Onion Powder', 58.61, 'erat curabitur gravida nisi', 482, 4537.12, 5, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (11, 'Chicken - Base, Ultimate', 24.44, 'fermentum donec ut', 394, 4599.56, 5, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (12, 'Versatainer Nc - 8288', 18.79, 'imperdiet nullam orci pede', 13, 332.65, 5, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (13, 'Bread Crumbs - Panko', 11.44, 'eleifend pede libero quis', 322, 4576.22, 2, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (14, 'Bouillion - Fish', 59.28, 'arcu sed augue aliquam', 412, 2226.62, 6, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (15, 'Tart - Butter Plain Squares', 72.47, 'at ipsum ac tellus semper', 382, 2865.17, 3, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (16, 'Pepsi - 600ml', 55.33, 'sapien ut nunc', 213, 3557.73, 4, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (17, 'Wine - Red, Pelee Island Merlot', 63.39, 'tempus vel pede morbi porttitor', 408, 4337.47, 2, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (18, 'Cumin - Ground', 26.2, 'semper sapien a libero', 42, 519.36, 2, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (19, 'Beans - Fava Fresh', 13.3, 'in consequat ut nulla', 40, 728.17, 5, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (20, 'Ham - Cooked', 43.38, 'elit proin interdum mauris non', 369, 3283.03, 4, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (21, 'Soup - Campbells Mac N Cheese', 47.53, 'venenatis non sodales sed', 380, 4092.34, 1, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (22, 'Cheese - Stilton', 72.19, 'eget orci vehicula', 405, 575.95, 2, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (23, 'Langers - Ruby Red Grapfruit', 27.79, 'turpis adipiscing lorem vitae', 366, 4036.86, 5, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (24, 'Mushroom - Portebello', 59.7, 'pretium iaculis diam erat', 489, 2730.57, 3, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (25, 'Milkettes - 2%', 46.09, 'ante ipsum primis in', 220, 2228.76, 2, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (26, 'Lettuce - Boston Bib', 74.41, 'diam erat fermentum justo', 215, 3068.13, 1, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (27, 'Papadam', 5.21, 'eros elementum pellentesque', 88, 2899.09, 1, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (28, 'Trout - Rainbow, Fresh', 35.24, 'turpis nec euismod scelerisque quam', 192, 2377.08, 2, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (29, 'Pasta - Penne, Lisce, Dry', 2.52, 'scelerisque mauris sit', 41, 1540.24, 3, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (30, 'Red Currant Jelly', 15.92, 'cubilia curae duis faucibus accumsan odio', 319, 3313.27, 1, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (31, 'Coconut - Shredded, Sweet', 61.98, 'ac neque duis bibendum morbi', 396, 142.82, 4, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (32, 'Huck Towels White', 39.17, 'convallis duis consequat dui nec', 343, 2410.68, 3, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (33, 'Huck White Towels', 36.79, 'molestie sed justo pellentesque viverra pede', 97, 4877.92, 6, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (34, 'Bread - Corn Muffaletta', 16.82, 'non lectus aliquam', 398, 520.08, 6, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (35, 'Fib N9 - Prague Powder', 6.83, 'imperdiet nullam orci pede venenatis', 425, 3700.23, 4, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (36, 'Bacardi Limon', 59.28, 'mattis odio donec vitae', 330, 179.75, 1, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (37, 'Ham - Cooked', 4.67, 'mauris non ligula pellentesque ultrices', 198, 3112.4, 6, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (38, 'Buffalo - Tenderloin', 12.12, 'ut massa quis', 248, 1502.19, 1, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (39, 'Orange - Tangerine', 64.46, 'integer aliquet massa id lobortis', 426, 1786.31, 1, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (40, 'Pasta - Penne, Lisce, Dry', 52.71, 'curae nulla dapibus', 217, 3123.78, 5, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (41, 'Pectin', 33.66, 'quam a odio', 488, 2018.37, 5, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (42, 'Wine - Red, Black Opal Shiraz', 54.63, 'aliquam quis turpis eget elit', 229, 8.46, 3, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (43, 'Basil - Dry, Rubbed', 73.13, 'pellentesque at nulla', 388, 447.3, 6, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (44, 'Bread - Triangle White', 29.04, 'lorem quisque ut erat curabitur', 186, 782.13, 5, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (45, 'Tea - Herbal Orange Spice', 39.11, 'quis tortor id nulla ultrices aliquet', 178, 2516.83, 2, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (46, 'Sauce - Vodka Blush', 6.22, 'natoque penatibus et', 154, 3795.5, 3, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (47, 'Sambuca - Ramazzotti', 74.59, 'sed ante vivamus tortor duis', 156, 2571.75, 1, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (48, 'Sugar - Monocystal / Rock', 70.73, 'sapien quis libero nullam sit amet', 379, 3410.37, 6, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (49, 'Pernod', 33.93, 'vel pede morbi porttitor lorem id', 223, 3690.76, 4, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (50, 'Swordfish Loin Portions', 25.89, 'vitae consectetuer eget rutrum', 384, 3009.14, 1, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (51, 'Milk - Chocolate 250 Ml', 78.04, 'urna pretium nisl ut volutpat sapien', 278, 1940.71, 2, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (52, 'Pepper - Cayenne', 55.38, 'in porttitor pede', 239, 1398.98, 3, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (53, 'Tuna - Fresh', 42.17, 'vestibulum ante ipsum primis in faucibus', 278, 1140.32, 1, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (54, 'Scallops - 20/30', 52.27, 'scelerisque quam turpis', 419, 2473.2, 6, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (55, 'Pork - Shoulder', 23.27, 'eget massa tempor convallis', 231, 4263.76, 1, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (56, 'Coffee - Irish Cream', 28.64, 'sociis natoque penatibus et magnis dis', 369, 82.12, 4, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (57, 'Beef - Tenderloin', 6.69, 'sit amet sem fusce consequat nulla', 490, 3756.26, 3, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (58, 'Toamtoes 6x7 Select', 75.66, 'ipsum praesent blandit lacinia', 200, 1555.79, 3, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (59, 'Table Cloth 62x114 White', 10.28, 'ultrices posuere cubilia', 332, 1460.27, 1, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (60, 'Water Chestnut - Canned', 12.51, 'magna at nunc commodo', 390, 4678.59, 2, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (61, 'Cherries - Maraschino,jar', 70.39, 'vulputate ut ultrices vel augue', 43, 803.5, 3, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (62, 'Muffin Hinge - 211n', 45.29, 'mauris sit amet eros', 288, 1346.78, 3, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (63, 'Olives - Black, Pitted', 68.51, 'sem sed sagittis nam congue', 296, 3499.07, 3, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (64, 'Tomatoes - Roma', 47.04, 'nam nulla integer pede', 195, 2795.53, 6, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (65, 'Creme De Menthe Green', 60.5, 'scelerisque quam turpis adipiscing lorem', 107, 1255.06, 2, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (66, 'Muffin - Carrot Individual Wrap', 9.64, 'nec condimentum neque', 62, 3517.92, 1, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (67, 'Versatainer Nc - 888', 11.13, 'non interdum in', 82, 4171.32, 2, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (68, 'Rabbit - Frozen', 47.51, 'id pretium iaculis diam', 400, 2593.89, 4, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (69, 'Flavouring Vanilla Artificial', 29.81, 'bibendum felis sed interdum', 8, 4827.54, 6, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (70, 'Salami - Genova', 35.55, 'vel enim sit amet nunc', 390, 2557.91, 4, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (71, 'Wine - Touraine Azay - Le - Rideau', 64.11, 'nisl venenatis lacinia aenean', 194, 799.12, 4, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (72, 'Wine - White Cab Sauv.on', 66.22, 'pulvinar sed nisl nunc rhoncus dui', 78, 3003.67, 2, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (73, 'Wine - Chateau Bonnet', 77.8, 'accumsan tortor quis', 131, 4453.15, 1, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (74, 'Campari', 38.31, 'interdum in ante vestibulum ante ipsum', 14, 3418.18, 1, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (75, 'Cheese - Manchego, Spanish', 63.3, 'justo eu massa', 306, 3822.33, 1, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (76, 'Squash - Butternut', 3.31, 'nisi venenatis tristique fusce congue diam', 29, 4903.35, 4, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (77, 'Wine - Crozes Hermitage E.', 25.25, 'turpis eget elit sodales scelerisque mauris', 383, 4241.16, 3, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (78, 'Wine - Chardonnay Mondavi', 41.7, 'metus vitae ipsum aliquam non mauris', 120, 3985.86, 5, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (79, 'Lotus Leaves', 68.23, 'dui vel nisl duis ac', 318, 891.02, 3, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (80, 'Food Colouring - Orange', 41.49, 'lacinia aenean sit amet justo morbi', 431, 4006.56, 5, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (81, 'Salmon - Canned', 74.15, 'blandit lacinia erat vestibulum', 444, 107.47, 5, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (82, 'Chocolate - Milk Coating', 45.78, 'morbi non lectus aliquam', 378, 1830.28, 3, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (83, 'Chinese Foods - Thick Noodles', 75.04, 'pede libero quis orci nullam', 250, 2256.91, 1, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (84, 'Rice - Brown', 60.2, 'aenean lectus pellentesque eget', 213, 3009.62, 2, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (85, 'Sausage - Blood Pudding', 51.83, 'tincidunt lacus at velit vivamus vel', 55, 1100.1, 3, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (86, 'Cake - Miini Cheesecake Cherry', 52.48, 'lorem vitae mattis nibh ligula nec', 379, 517.62, 3, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (87, 'Tabasco Sauce, 2 Oz', 25.29, 'consequat lectus in est', 125, 867.26, 5, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (88, 'Bread - Assorted Rolls', 53.42, 'maecenas rhoncus aliquam lacus morbi quis', 435, 4257.94, 4, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (89, 'Beer - Sleemans Cream Ale', 26.99, 'dapibus at diam nam tristique tortor', 174, 2050.36, 1, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (90, 'Napkin - Beverage 1 Ply', 57.99, 'faucibus orci luctus et ultrices posuere', 349, 3855.48, 4, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (91, 'Spice - Greek 1 Step', 39.54, 'ac leo pellentesque ultrices', 200, 994.01, 3, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (92, 'Flower - Commercial Bronze', 11.17, 'quisque ut erat curabitur gravida nisi', 243, 4310.43, 3, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (93, 'Olives - Morracan Dired', 58.66, 'elit proin risus praesent', 15, 1528.75, 6, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (94, 'Onions - Pearl', 28.22, 'auctor gravida sem', 220, 4321.82, 4, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (95, 'Curry Paste - Madras', 58.94, 'consequat in consequat ut nulla sed', 165, 4185.88, 3, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (96, 'Sambuca - Ramazzotti', 51.47, 'curabitur gravida nisi', 435, 1732.8, 1, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (97, 'Sauce - Soy Low Sodium - 3.87l', 55.06, 'nunc commodo placerat praesent blandit nam', 372, 3607.98, 4, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (98, 'Pork - Bacon Cooked Slcd', 14.53, 'adipiscing molestie hendrerit at vulputate vitae', 27, 3450.07, 3, true);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (99, 'Pork - Backs - Boneless', 48.53, 'dui vel sem sed', 441, 4325.98, 4, false);
insert into products (pk_product, name_product, weight, description, stock, price, fk_product_category, status) values (100, 'Cake - Mini Potato Pancake', 43.33, 'habitasse platea dictumst etiam', 204, 3264.75, 3, false);



-- Tabla orders


insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (1, '72 Stoughton Way', '2022-05-30', true, 3428.619, 83, 1);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (2, '5912 Dunning Avenue', '2022-06-09', false, 2635.15, 6, 1);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (3, '4817 Ruskin Terrace', '2022-04-05', false, 5169.515, 51, 4);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (4, '28 Ryan Center', '2021-11-02', false, 9898.054, 43, 8);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (5, '78 Sutteridge Pass', '2022-03-04', true, 2304.682, 2, 7);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (6, '70 Toban Hill', '2022-01-03', false, 5184.51, 90, 2);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (7, '58990 Roth Circle', '2022-02-03', false, 7892.609, 38, 8);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (8, '348 Monument Lane', '2022-02-28', true, 3213.025, 10, 4);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (9, '4 Petterle Drive', '2022-07-13', true, 6030.834, 60, 4);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (10, '165 Declaration Alley', '2022-03-11', false, 1945.41, 34, 2);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (11, '656 Golf View Circle', '2022-03-01', false, 5156.04, 31, 8);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (12, '84395 Graceland Lane', '2021-12-25', false, 219.313, 34, 7);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (13, '99 Fulton Hill', '2021-12-26', false, 4078.462, 86, 1);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (14, '8167 Ridge Oak Plaza', '2021-11-04', true, 8812.246, 3, 6);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (15, '04 Daystar Junction', '2022-06-15', false, 329.417, 85, 2);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (16, '62496 Harper Terrace', '2021-12-05', true, 9146.831, 42, 6);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (17, '22 Bashford Lane', '2022-07-12', false, 2948.273, 67, 1);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (18, '00 Tony Trail', '2021-09-27', false, 627.755, 41, 8);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (19, '639 Pankratz Road', '2021-09-02', false, 2283.251, 76, 5);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (20, '8774 Bonner Park', '2021-08-03', false, 8335.05, 55, 4);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (21, '688 Golf Course Trail', '2022-05-29', true, 3549.463, 5, 7);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (22, '45 Fordem Street', '2022-06-18', true, 580.791, 11, 6);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (23, '0 Leroy Alley', '2022-03-06', true, 5182.769, 24, 7);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (24, '9 Little Fleur Parkway', '2022-03-07', false, 2864.912, 91, 6);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (25, '05405 Leroy Drive', '2022-06-05', false, 8003.615, 77, 2);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (26, '12185 Farwell Crossing', '2021-08-19', false, 5343.969, 29, 3);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (27, '78 Bunting Road', '2022-01-21', false, 8847.488, 40, 3);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (28, '64518 Warbler Place', '2021-12-30', true, 5499.72, 38, 3);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (29, '80854 Spaight Road', '2021-12-05', false, 4847.26, 56, 5);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (30, '43 Chive Trail', '2022-04-27', false, 1623.461, 45, 5);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (31, '83497 Debra Way', '2021-08-11', true, 7333.613, 57, 6);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (32, '8 Monterey Lane', '2021-10-29', true, 2032.14, 86, 6);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (33, '457 Superior Parkway', '2022-02-08', true, 3674.561, 70, 5);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (34, '4954 Di Loreto Place', '2022-06-19', true, 9882.104, 7, 1);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (35, '9871 Sutherland Circle', '2021-10-21', false, 2612.757, 28, 4);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (36, '13 Badeau Terrace', '2021-09-11', true, 6993.048, 34, 5);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (37, '5818 Northwestern Terrace', '2022-02-28', true, 9959.871, 62, 3);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (38, '8 Talmadge Drive', '2021-11-22', false, 6670.668, 24, 3);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (39, '0 Fisk Avenue', '2021-07-27', true, 8841.867, 70, 2);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (40, '844 Lerdahl Drive', '2021-12-08', true, 3581.469, 72, 8);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (41, '82 Arizona Center', '2021-07-26', true, 9281.942, 14, 8);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (42, '8667 Butterfield Junction', '2022-02-11', false, 6550.449, 46, 3);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (43, '69 Anderson Place', '2022-01-27', false, 6165.549, 2, 3);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (44, '5852 3rd Street', '2022-01-08', false, 4594.555, 84, 5);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (45, '6 Fremont Lane', '2021-08-10', false, 3466.824, 30, 5);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (46, '64206 Sherman Place', '2022-03-30', false, 190.814, 25, 8);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (47, '3164 Glendale Plaza', '2022-02-11', true, 3137.896, 9, 2);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (48, '952 Oak Valley Parkway', '2022-04-20', true, 5858.438, 12, 8);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (49, '0 Maryland Center', '2022-02-16', true, 8382.976, 94, 6);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (50, '05 Sugar Court', '2022-02-22', true, 2804.528, 67, 5);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (51, '399 Goodland Hill', '2022-05-05', true, 7970.284, 17, 4);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (52, '19186 Dapin Alley', '2022-01-19', true, 7794.575, 93, 4);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (53, '694 Division Court', '2022-07-03', true, 3512.308, 59, 2);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (54, '11 Bluejay Court', '2022-01-29', false, 6615.531, 12, 3);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (55, '21 Myrtle Drive', '2021-11-30', true, 5316.437, 90, 7);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (56, '5806 Scoville Plaza', '2022-06-30', true, 3082.873, 7, 4);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (57, '746 Browning Avenue', '2021-10-06', true, 4774.777, 80, 3);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (58, '10401 Browning Hill', '2021-08-16', false, 4182.209, 46, 3);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (59, '97224 Randy Hill', '2022-06-08', false, 338.169, 81, 5);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (60, '51 Thompson Terrace', '2022-03-09', true, 4521.954, 60, 8);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (61, '68 Randy Terrace', '2022-07-18', false, 5874.208, 38, 3);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (62, '077 Fuller Hill', '2021-12-02', true, 8507.475, 92, 4);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (63, '99 Hagan Lane', '2022-06-07', false, 8342.224, 81, 5);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (64, '47 Fair Oaks Way', '2021-12-01', true, 7026.987, 53, 7);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (65, '3101 Gale Street', '2022-05-30', true, 5318.79, 92, 6);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (66, '13 North Park', '2021-08-08', false, 4684.729, 53, 4);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (67, '15111 Becker Trail', '2022-02-23', true, 9157.127, 60, 1);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (68, '4 Mayer Parkway', '2022-02-05', false, 2379.261, 32, 5);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (69, '687 Ilene Place', '2022-05-02', false, 363.277, 8, 2);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (70, '5 Vahlen Pass', '2022-07-24', true, 9357.035, 9, 3);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (71, '46755 Oakridge Court', '2022-01-30', true, 799.882, 33, 2);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (72, '8952 Waywood Junction', '2022-01-19', true, 975.216, 48, 8);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (73, '51 Sunnyside Drive', '2021-11-14', false, 5847.371, 78, 2);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (74, '05603 Bashford Place', '2021-09-22', false, 6721.028, 54, 7);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (75, '2942 Browning Plaza', '2022-02-09', true, 7519.3, 91, 6);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (76, '8147 Anthes Street', '2022-07-19', false, 376.38, 92, 1);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (77, '104 Holy Cross Lane', '2021-11-18', false, 690.788, 82, 8);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (78, '421 Thackeray Terrace', '2021-09-18', true, 8779.037, 64, 1);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (79, '44085 Jackson Park', '2022-03-08', true, 8747.492, 3, 2);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (80, '9 Thompson Road', '2021-08-01', true, 1405.194, 46, 2);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (81, '178 Montana Court', '2021-10-14', true, 1983.378, 67, 5);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (82, '3023 Meadow Ridge Park', '2021-12-18', true, 2232.682, 42, 6);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (83, '04172 Chinook Point', '2021-09-02', true, 3465.845, 35, 5);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (84, '619 Harper Drive', '2021-09-11', true, 8642.067, 15, 8);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (85, '790 Mallory Parkway', '2021-09-07', true, 2789.631, 77, 6);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (86, '146 Charing Cross Avenue', '2022-01-20', true, 1999.361, 29, 4);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (87, '3 Erie Alley', '2022-05-15', true, 7640.698, 77, 8);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (88, '2453 Pankratz Alley', '2021-10-28', false, 8966.658, 96, 5);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (89, '1 Walton Junction', '2021-12-10', false, 5775.689, 99, 6);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (90, '153 Randy Avenue', '2022-06-28', false, 9190.077, 29, 3);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (91, '593 Crest Line Trail', '2021-11-25', true, 1799.576, 10, 2);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (92, '22 Lakewood Gardens Place', '2021-11-26', true, 3976.848, 39, 8);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (93, '2 Shopko Junction', '2021-08-16', false, 9661.343, 79, 6);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (94, '10822 Armistice Parkway', '2021-11-03', false, 5560.286, 33, 8);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (95, '13308 Del Sol Point', '2022-01-14', true, 7023.832, 94, 5);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (96, '162 Express Parkway', '2022-02-07', true, 8272.621, 39, 8);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (97, '8 Blackbird Plaza', '2021-08-07', true, 7678.915, 29, 1);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (98, '7888 Sloan Way', '2021-12-29', false, 9693.004, 94, 1);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (99, '873 Sutherland Place', '2022-02-04', true, 7128.109, 60, 2);
insert into orders (pk_order, shipping_address, order_date, order_status, ammount, fk_customers, fk_delivery_countries) values (100, '94946 Aberg Lane', '2021-12-05', true, 3730.838, 66, 5);


-- Tabla order details


insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (1, 3137.07, 10, 67, 40.201, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (2, 6859.04, 28, 12, 36.203, 1);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (3, 996.57, 2, 87, 38.654, 6);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (4, 4938.14, 3, 87, 83.305, 7);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (5, 6834.72, 11, 40, 75.812, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (6, 6370.46, 2, 82, 76.265, 7);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (7, 1837.83, 7, 84, 4.042, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (8, 1356.92, 1, 26, 49.484, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (9, 4327.59, 26, 94, 77.382, 4);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (10, 1226.83, 17, 29, 41.636, 4);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (11, 257.19, 22, 7, 88.899, 6);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (12, 8134.6, 2, 15, 11.08, 2);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (13, 6.47, 1, 9, 13.419, 7);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (14, 9975.19, 4, 25, 42.091, 7);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (15, 8866.42, 17, 80, 51.973, 7);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (16, 6231.92, 37, 82, 21.389, 1);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (17, 4049.2, 11, 16, 70.047, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (18, 4904.11, 23, 31, 7.399, 1);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (19, 729.46, 31, 28, 23.287, 6);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (20, 5657.52, 26, 1, 48.49, 7);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (21, 7022.14, 13, 68, 25.414, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (22, 6573.93, 16, 84, 20.955, 4);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (23, 2014.75, 32, 88, 18.684, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (24, 7572.15, 18, 16, 18.625, 4);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (25, 4091.52, 22, 92, 9.939, 5);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (26, 2126.97, 24, 20, 67.357, 6);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (27, 3026.91, 2, 31, 34.771, 6);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (28, 6238.98, 12, 46, 58.732, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (29, 7042.1, 21, 35, 57.796, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (30, 6841.43, 25, 56, 79.796, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (31, 3688.38, 27, 71, 18.797, 2);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (32, 8877.54, 3, 97, 27.922, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (33, 4138.55, 7, 31, 59.373, 4);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (34, 7392.51, 18, 100, 28.166, 6);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (35, 7708.89, 18, 93, 17.16, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (36, 4283.9, 38, 89, 99.206, 7);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (37, 3888.26, 11, 54, 8.834, 5);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (38, 8878.81, 5, 67, 93.493, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (39, 1663.18, 17, 89, 53.788, 1);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (40, 4288.37, 38, 50, 88.922, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (41, 9512.49, 14, 82, 24.355, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (42, 3391.28, 9, 96, 99.713, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (43, 703.44, 21, 44, 8.677, 6);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (44, 3320.22, 20, 73, 94.221, 1);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (45, 68.05, 22, 13, 11.416, 6);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (46, 6832.16, 10, 46, 56.093, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (47, 1724.21, 4, 59, 85.808, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (48, 1757.88, 14, 24, 22.932, 5);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (49, 2804.73, 13, 35, 26.577, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (50, 2783.11, 27, 31, 73.269, 4);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (51, 6807.65, 35, 22, 32.849, 2);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (52, 9165.17, 9, 92, 54.123, 4);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (53, 8341.77, 32, 59, 61.985, 1);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (54, 5968.11, 13, 55, 42.978, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (55, 6932.56, 8, 9, 62.617, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (56, 3265.86, 22, 46, 77.767, 5);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (57, 8646.59, 21, 55, 62.753, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (58, 8219.15, 17, 91, 63.026, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (59, 3015.33, 19, 40, 53.621, 5);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (60, 3429.22, 32, 21, 63.702, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (61, 4535.43, 38, 73, 18.875, 5);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (62, 4039.46, 31, 9, 27.322, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (63, 1711.01, 39, 18, 13.76, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (64, 3096.14, 24, 18, 86.018, 4);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (65, 1581.18, 27, 66, 99.732, 5);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (66, 3952.51, 1, 31, 11.311, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (67, 5958.26, 21, 39, 61.238, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (68, 1533.4, 26, 57, 95.893, 5);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (69, 7618.79, 29, 31, 88.068, 1);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (70, 3651.14, 2, 25, 87.113, 2);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (71, 2992.22, 39, 24, 43.935, 7);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (72, 334.76, 29, 74, 89.278, 2);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (73, 8545.7, 9, 49, 54.687, 5);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (74, 1034.2, 18, 57, 4.65, 6);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (75, 9053.1, 6, 26, 58.539, 7);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (76, 5416.5, 26, 23, 66.221, 7);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (77, 8709.02, 18, 15, 51.367, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (78, 3440.56, 5, 85, 96.761, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (79, 5001.53, 15, 51, 39.039, 1);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (80, 4332.49, 2, 1, 96.162, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (81, 3142.67, 26, 23, 77.714, 7);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (82, 993.07, 35, 17, 13.123, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (83, 1637.09, 34, 51, 4.411, 5);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (84, 1779.59, 29, 31, 46.487, 7);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (85, 8591.43, 26, 48, 12.502, 4);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (86, 6097.18, 16, 96, 68.595, 7);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (87, 9185.06, 2, 80, 24.378, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (88, 639.09, 6, 19, 96.596, 5);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (89, 3183.03, 27, 22, 58.486, 4);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (90, 9302.79, 10, 30, 71.499, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (91, 1035.96, 21, 43, 71.149, 6);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (92, 701.18, 18, 53, 40.413, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (93, 4824.52, 4, 90, 87.975, 1);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (94, 402.7, 16, 82, 71.231, 7);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (95, 5619.9, 16, 94, 49.459, 6);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (96, 5528.76, 15, 3, 13.125, 6);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (97, 862.11, 36, 91, 50.482, 8);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (98, 8560.76, 19, 14, 46.371, 3);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (99, 6419.42, 12, 2, 84.542, 2);
insert into order_details (pk_order_details, price, quantity, fk_products, fk_order, fk_delivery_companies) values (100, 1633.0, 12, 88, 15.829, 7);